AWSTemplateFormatVersion: "2010-09-09"
Description: KMS CMK

Resources:
  AccessLogs:
    Type: AWS::Logs::LogGroup
    DependsOn: AccessLogsKMSKey
    Properties:
      RetentionInDays: 30
      KmsKeyId: !GetAtt AccessLogsKMSKey.Arn

  AccessLogsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'CMK for encrypting AccessLogs'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Allow administration of the key'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: 'Allow use of the key by CloudWatch Logs'
            Effect: Allow
            Principal:
              Service: !Sub 'logs.${AWS::Region}.amazonaws.com'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              ArnLike:
                'kms:EncryptionContext:aws:logs:arn': 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'

  AccessLogsKMSKeyAlias:
    Type: AWS::KMS::Alias
    DependsOn: AccessLogsKMSKey
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-AccessLogsKey'
      TargetKeyId: !Ref AccessLogsKMSKey

      
Outputs:
  KmsKeyId:
    Description: "The ARN of the KMS Key used for Access Logs"
    Value: !GetAtt AccessLogsKMSKey.Arn